default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: solidus_dev
  host: localhost
  user: sushi
  password: password

production:
  <<: *default
  database: beroot
  username: deploy
  password: password